include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
    require_trailing_commas: true
    avoid_relative_lib_imports: true
    use_build_context_synchronously: false
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
